// constants/quotes.ts
export const FUNNY_QUOTES = [
  "Cleaner than my own home!",
  "Five-star restroom experience!",
  "Found paradise on earth!",
  "Does this place have WiFi?",
  "More comfortable than a café!",
  "Finally found it!",
  "Spotless perfection!",
  "Will definitely come back!",
  "Fully equipped facilities!",
  "Beyond expectations!",
  "They have toilet paper! Amazing!",
  "Perfect lighting and ambiance!",
  "Better than I imagined!",
  "Finally, relief at last!",
  "New and super clean facilities!",
  "This is restroom luxury!",
  "I could live here!",
  "Better than some hotels!",
  "Emergency mission accomplished!",
  "Nature called, and it answered!",
  "Throne room worthy!",
  "VIP bathroom treatment!",
  "My new favorite spot!",
  "Crystal clear facilities!",
  "Royal flush approved!",
  "Bathroom goals achieved!",
  "Pristine and perfect!",
  "Top-tier toilet experience!",
  "Squeaky clean success!",
  "Facilities fit for a king!",
];